---
- name: Install base packages
  apt:
    name: "{{packages}}"
    state: present
    update_cache: yes
  vars:
    packages:
    - zsh

- name: Copy Powerlevel10k config file
  copy:
    src: p10k.zsh
    dest: "/home/{{admin_user}}/.p10k.zsh"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"

- name: Install other plugins
  include_tasks: "{{item}}"
  with_items:
  #- zprezto.yml
  - ohmyzsh.yml

- name: Custom zsh options
  template:
    src: zshrc
    dest: "/home/{{admin_user}}/.zshrc"
    owner: "{{admin_user}}"
    group: "{{admin_user}}"
