- name: Download oh-my-zsh install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install.sh
    mode: 0755

- name: Install oh-my-zsh
  ansible.builtin.command:
    cmd: /tmp/install.sh
    creates: "/home/{{admin_user}}/.oh-my-zsh"
  become_user: "{{admin_user}}"
  
- name: Install powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "/home/{{admin_user}}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1

- name: Install zsh plugins
  git:
    repo: "{{plugin.value.url}}"
    dest: "/home/{{admin_user}}/.oh-my-zsh/custom/plugins/{{plugin.key}}"
    depth: 1
  with_dict: "{{zsh_plugins}}"
  loop_control:
    loop_var: plugin
  become_user: "{{admin_user}}"
